pipeline {
    agent any

    environment {
        PATH = "C:/Program Files/gradle-8.7/bin;${env.PATH}"
        DOCKER_REGISTRY = 'elllliif/java-app'
        DOCKER_CREDENTIALS = 'DHub-1'
        DOCKER_IMAGE = ' '
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/elllliif/devops-project3.git'
                dir('project3') {
                    echo 'Switched to project3 directory'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    dir('project3') {
                        bat './gradlew clean build'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('project3') {
                        DOCKER_IMAGE = docker.build("${DOCKER_REGISTRY}:latest")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', DOCKER_CREDENTIALS) {
                        DOCKER_IMAGE.push()
                    }
                }
            }
        }
    }
    stages {
            stage('Apply PostgreSQL YAML') {
                steps {
                    script {
                        def applied = kubernetesApply(yaml: 'postgres.yml')
                        if (applied) {
                            echo 'PostgreSQL YAML applied successfully'
                        } else {
                            error 'Failed to apply PostgreSQL YAML'
                        }
                    }
                }
            }
            stage('Apply Spring Boot App YAML') {
                steps {
                    script {
                        def applied = kubernetesApply(yaml: 'spring-boot-app.yml')
                        if (applied) {
                            echo 'Spring Boot App YAML applied successfully'
                        } else {
                            error 'Failed to apply Spring Boot App YAML'
                        }
                    }
                }
            }

    post {
        success {
            echo 'Everything is fine.'
        }
        failure {
            echo 'Something went wrong.'
        }
    }
}
