apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres-sample
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: spring-boot-postgres-sample
      labels:
        app: webapp
    spec:
      containers:
      - name: spring-boot-postgres-sample
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_host
        image: elllliif/java-app:latest
  selector:
    matchLabels:
      app: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 32140
      protocol: TCP
