apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 32140
      protocol: TCP